### ISSUE TITLE
blockchain-node ref to commit that was deleted

### ISSUE THREAD

**Issue by APshenkin** [helium/blockchain-node#133]
Build fails with this error for latest blockchain-node tag

```
Fetching grpcbox (from {git,"https://github.com/novalabsxyz/grpcbox.git",
                   {ref,"5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}})
===> Failed to fetch and copy dep: {git,
                                  "https://github.com/novalabsxyz/grpcbox.git",
                                  {ref,
                                      "5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}}
```

**Comment by madninja** [comment]
Fixed with #134

**Comment by joslee7410** [comment]
```
===> Fetching erl_base58 v0.0.1
===> Fetching rebar3_hex v7.0.1
===> Fetching hex_core v0.8.4
===> Fetching verl v1.1.1
===> Analyzing applications...
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Fetching erlang_stats (from {git,"https://github.com/helium/erlang-stats.git",
                        {ref,"ba2d545f8e559bd4d46146a5f5277ce4f907c03f"}})
===> Fetching exor_filter (from {git,"https://github.com/mpope9/exor_filter",
                       {ref,"36a15cf1c12eac7563cc7d50328f2bc53ceb2687"}})
===> Fetching grpc_client (from {git,"https://github.com/Bluehouse-Technology/grpc_client.git",
                       {ref,"04c24590a23b22ec5bd87e7f4ba92152310a41b6"}})
===> Fetching grpcbox (from {git,"https://github.com/novalabsxyz/grpcbox.git",
                   {ref,"5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}})
===> Failed to fetch and copy dep: {git,
                                  "https://github.com/novalabsxyz/grpcbox.git",
                                  {ref,
                                      "5cca01a52b6bb4c8dbadf1fe7f6441a350308235"}}
GNUmakefile:43: recipe for target 'src/grpc/autogen' failed
make[1]: *** [src/grpc/autogen] Error 1
make[1]: Leaving directory '/disk2/hnt/hnt2/blockchain-node/_build/default/lib/blockchain'
===> Hook for compile failed!
```

I'm still getting the same error. Already switch to fixed brunch

`HEAD is now at 4dcdf50 Merge pull request #134 from ci-work/patch-3`
